spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/llh2
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#  messages:
#    basename: victim
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  file:
    name: dvdRental.log

app:
  initializer:
    version: 1